[package]
name = "tiwtor"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.5", features = ["sqlite"] }
dotenvy = "0.15.7"
inquire = "0.7.5"
lecsicon-db = { path = "../lecsicon-db" }
